### ISSUE TITLE
"This browser does not support ResizeObserver out of the box." on Jest (on node)

### ISSUE THREAD

**Issue by kimmoonil** [airbnb/visx#1576]
This browser does not support ResizeObserver out of the box.
```
 This browser does not support ResizeObserver out of the box. See: https://github.com/react-spring/react-use-measure/#resize-observer-polyfills

      62 |   }, [clicks, dimensions, theme])
      63 |
    > 64 |   const { containerRef, TooltipInPortal } = useTooltipInPortal({
         |                                             ^
      65 |     scroll: true,
      66 |   })
      67 |

      at useMeasure (../../node_modules/react-use-measure/dist/web.cjs.js:24:11)
      at useTooltipInPortal (../../node_modules/@visx/tooltip/lib/hooks/useTooltipInPortal.js:40:50)
```

Can I fix it? 😢

**Comment by MJ9001** [comment]
Add this mock class somewhere:
class ResizeObserver {
  observe() {
    // do nothing
  }
  unobserve() {
    // do nothing
  }
  disconnect() {
    // do nothing
  }
}

In your jest test add this:
    window.ResizeObserver = ResizeObserver;

**Comment by kimmoonil** [comment]
> 

thx!!!
