### ISSUE TITLE
Getting Runtime Error

### ISSUE THREAD

**Issue by ashwith2427** [airbnb/visx#1887]
Iam getting the runtime error when I put AnimatedGrid and AnimatedAxis components in my code and the error goes like this. 

```

(0,web.useTransition) is not a function

TypeError: (e,web.useTransition) is not a function

at AnimatedGridLines (http://localhost:3000/static/js/bundle.js:7736:46)

at renderWithHooks (http://localhost:3000/static/js/bundle.js:58977:22)

at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:62948:17)

at beginwork (http://localhost:3000/static/js/bundle.js:64251:20)

at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:49233:

at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:49277:

at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:49334:35)

at beginWork$1 (http://localhost:3000/static/js/bundle.js:69232:11)

at performUnitofwork (http://localhost:3000/static/js/bundle.js:68480:16)

at workLoopSync (http://localhost:3000/static/js/bundle.js:68403:9)
```
My package.json is

```json
"dependencies": {

"@babel/core": "7.26.0",

"@babel/runtime": "^7.2.6",

"@react-spring/web": "^9.4.5",

"@testing-library/jest-dom": "^5.17.8",

"@testing-library/react": "^13.4.0", "@testing-library/user-event": "^13.5.0",

"@types/react": "^18",

"@types/react-dom": "^18",

"@visx/curve": "1.0.0",

"@visx/glyph": "3.12.0",

"@visx/mock-data": "3.12.0",

"@visx/pattern": "3.12.8",

"@visx/react-spring": "3.12.0", "@visx/responsive": "3.12.0",

"@visx/visx": "^3.12.8", "@visx/xychart": "^3.12.0",

"@waypoint/react-components": "^5.17.0",

"babel-runtime": "^6.26.0",

"react": "^18.3.1",

"react-dom": "^18.3.1",

"react-router-dom": "latest",

"react-scripts":"^5.0.1",

"react-spring": "^9.7.4",

"typescript": "^3.9.10",

"web-vitals": "^2.1.4"
}

**Comment by williaster** [comment]
Hey @ashwith2427 can you make this reproducible in a sandbox? that's easier to debug.

**Comment by ashwith2427** [comment]
I have just took it from examples. Sample area series example with temperatures data as input .

**Comment by williaster** [comment]
duplicates https://github.com/airbnb/visx/issues/1725
